source 'https://rubygems.org'

gem "awestruct", '0.5.0.cr'
gem 'rb-inotify', '~> 0.8.8'
gem 'rack-test'
gem 'tilt', '>= 1.3.4'
gem 'asciidoctor', '>= 0.1.0'
gem 'haml', '~> 4.0.0'
gem 'kramdown', '~> 0.14.2'
gem 'minify'
gem 'therubyrhino', '~> 1.73', :platforms => :jruby
gem 'RedCloth', '~> 4.2.9'
gem 'coffee-script', '~> 2.2.0'
gem 'uglifier', '~> 1.3.0'
gem 'htmlcompressor'