encoding: UTF-8

asciidoctor:
  :attributes:
    imagesdir: '/'

profiles:
  development:
    robots: ['/']
    base_url: http://stewie:4242
  production:
    disqus: outjected
    g_analytics: true
    robots: ['google5576bee535bb3234.html']
    change_frequency: weekly
    base_url: https://www.outjected.com
    deploy:
      host: awestruct@oxygen.clearfly.net
      path: /var/www/outjected.com
      uncommitted: true