profiles:
  development:
    base_url: http://stewie:4242
  production:
    disqus: outjected
    disqus_generate_id: true
    google_analytics: UA-32753867-2
    base_url: http://www.outjected.com
    deploy:
      host: awestruct@tin.clearfly.net
      path: /var/www/outjected.com