---
title: "Seam Mail 3.1.1.Final Released"
layout: blog
author: Cody Lerum
email: cody.lerum@gmail.com
tags: [ java, seam, email ]
---
==== Obligatory Links and Compatibility

I'm happy to announce that I've released a minor update to http://www.seamframework.org/Seam3/Mail[Seam 3 Mail]
versioned https://repository.jboss.org/nexus/index.html#nexus-search;quick~seam-mail[3.1.1.Final]. This is a minor
release which is compatible with http://in.relation.to/Bloggers/JBossSeam31FinalReleased[Seam 3.1.0.Final].

==== Whats new?

The main goal of this release was to fill in some gaps in documentation as well as some minor bug fixes which popped up
since the 3.1.0.Final release. I've also added in a utility class called
https://github.com/seam/mail/blob/develop/impl/src/main/java/org/jboss/seam/mail/util/MessageConverter.java[MessageConverter]
which allows you to read a MimeMessage back into the internal EmailMessage object used by Seam Mail. This opens up the
option for Seam Mail to receive messages in addition to sending them. Check out
https://issues.jboss.org/browse/SEAMMAIL/fixforversion/12318997#selectedTab=com.atlassian.jira.plugin.system.project%3Aversion-issues-panel[Closed Issues]
on the JIRA tracker for details.

==== What does future look like?

Seam 3 Mail will continue to provide releases in its current format until the time comes for it to transition to
http://incubator.apache.org/deltaspike/[Apache DeltaSpike]. In the meantime if you have features for fixes to contribute
just open a http://jira.jboss.org/browse/SEAMMAIL[JIRA] and I'll be happy to work them in.

==== How about an example?

POP3+SSL to receive an MimeMessage and convert it. It's basically for gmail but with values changed to protect the
innocent.

[source,java]
----
import java.util.Properties;

import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.URLName;

import org.jboss.seam.mail.core.EmailMessage;
import org.jboss.seam.mail.util.MessageConverter;

import com.sun.mail.pop3.POP3SSLStore;

public class Popper {

    public static void main(String[] args) throws Exception {

        String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";

        Properties pop3Props = new Properties();

         pop3Props.setProperty("mail.pop3.socketFactory.class", SSL_FACTORY);
         pop3Props.setProperty("mail.pop3.socketFactory.fallback", "false");
         pop3Props.setProperty("mail.pop3.port", "995");
         pop3Props.setProperty("mail.pop3.socketFactory.port", "995");

         URLName url = new URLName("pop3", "pop.example.com", 995, "", "foo@example.com", "mypass");

         Session session = Session.getInstance(pop3Props, null);
         Store store = new POP3SSLStore(session, url);
         store.connect();

         Folder inbox = store.getFolder("INBOX");
         inbox.open(Folder.READ_ONLY);

         Message[] messages = inbox.getMessages();

         if (messages.length == 0) {
             System.out.println("No Messages Found");
         }

         List<EmailMessage> emailMessages = new ArrayList<EmailMessage>();

         for (Message m : messages) {
             emailMessages.add(MessageConverter.convert(m));
         }

         inbox.close(false);
         store.close();
    }
}
----
